/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    GiphyContainer: typeof import('./components/GiphyContainer.vue')['default']
    GiphyGif: typeof import('./components/GiphyGif.vue')['default']
    GiphyLogo: typeof import('./components/GiphyLogo.vue')['default']
    GiphyOriginal: typeof import('./components/GiphyOriginal.vue')['default']
    GiphyPreview: typeof import('./components/GiphyPreview.vue')['default']
    GiphySearch: typeof import('./components/GiphySearch.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NotFound: typeof import('./components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
